# Prometheus configuration for monitoring Celery

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'celery'
    static_configs:
      - targets: ['localhost:8888']
    metrics_path: /metrics
